### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by rjollos** [lachlan-00/utidylib2#1]
Hi, would you consider publishing this package to PyPI? A project in trac-hacks currently lists it as a dependency, so installation with easy_install will fail.

http://trac-hacks.org/wiki/OdtExportPlugin

**Comment by rjollos** [comment]
If you'd like I could publish the package to PyPI and then make you owner of the package. Do you have an account on PyPI already?

**Comment by lachlan-00** [comment]
i don't, i created this repo as the original berlios site was taken down and michael cihar posted about it. i'm happy to keep this open and apply any patches.
